-- Supabase setup for bashuduhou.top
-- Run this in Supabase Dashboard -> SQL Editor.

create table if not exists public.comments (
    id bigint generated by default as identity primary key,
    lesson_id text not null,
    text text not null default '',
    time_str text not null default '',
    user_hash text not null,
    parent_id bigint references public.comments(id) on delete cascade,
    image_urls jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.comments
    add column if not exists image_urls jsonb not null default '[]'::jsonb;

alter table public.comments enable row level security;

drop policy if exists "comments are readable" on public.comments;
create policy "comments are readable"
on public.comments
for select
to anon
using (true);

drop policy if exists "comment authors can insert" on public.comments;
create policy "comment authors can insert"
on public.comments
for insert
to anon
with check (
    user_hash = nullif(current_setting('request.headers', true)::json ->> 'x-user-hash', '')
);

drop policy if exists "comment authors can delete own comments" on public.comments;
create policy "comment authors can delete own comments"
on public.comments
for delete
to anon
using (
    user_hash = nullif(current_setting('request.headers', true)::json ->> 'x-user-hash', '')
);

create index if not exists comments_lesson_created_idx
on public.comments (lesson_id, created_at);

create index if not exists comments_parent_idx
on public.comments (parent_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'comment-images',
    'comment-images',
    true,
    5242880,
    array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "comment images are publicly readable" on storage.objects;
create policy "comment images are publicly readable"
on storage.objects
for select
to anon
using (bucket_id = 'comment-images');

drop policy if exists "comment authors can upload images" on storage.objects;
create policy "comment authors can upload images"
on storage.objects
for insert
to anon
with check (
    bucket_id = 'comment-images'
    and (storage.foldername(name))[2] = nullif(current_setting('request.headers', true)::json ->> 'x-user-hash', '')
);
